# Generated by Django 6.0.4 on 2026-05-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_remove_project_advance_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="advance_amount_incl_vat",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional. Leave blank if client pays no advance.",
                max_digits=14,
                null=True,
                verbose_name="Client advance (incl. VAT)",
            ),
        ),
    ]
