# Generated by Django 6.0.4 on 2026-05-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Date"),
        ),
    ]
