# Generated by Django 6.0.4 on 2026-05-04 02:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyPayable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_name", models.CharField(max_length=255)),
                ("total_payable", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("date_last_paid", models.DateField(blank=True, null=True)),
                ("projects_name", models.CharField(blank=True, max_length=255)),
                ("status_note", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Legacy payable",
                "verbose_name_plural": "Legacy payables",
                "ordering": ["supplier_name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "flow_type",
                    models.CharField(
                        choices=[("IN", "IN"), ("OUT", "OUT")],
                        db_index=True,
                        max_length=3,
                    ),
                ),
                (
                    "amount_excl_vat",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("account", models.CharField(db_index=True, max_length=64)),
                ("category", models.CharField(db_index=True, max_length=128)),
                ("material_item", models.CharField(blank=True, max_length=255)),
                (
                    "qty",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("party_name", models.CharField(blank=True, max_length=255)),
                ("party_type", models.CharField(blank=True, max_length=64)),
                ("invoice_number", models.CharField(blank=True, max_length=128)),
                (
                    "tax_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("payment_status", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["date", "flow_type"], name="transaction_date_31ea01_idx"
                    ),
                    models.Index(
                        fields=["account", "flow_type"],
                        name="transaction_account_17e332_idx",
                    ),
                ],
            },
        ),
    ]
