# Generated by Django 6.0.4 on 2026-05-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Bank", "Bank"),
                    ("Accounts Receivable", "Accounts Receivable"),
                    ("Accounts Payable", "Accounts Payable"),
                    ("Employee Advance", "Employee Advance"),
                    ("Employee Payable", "Employee Payable"),
                    ("Owner Contribution", "Owner Contribution"),
                    ("Owner Drawings", "Owner Drawings"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("Material Purchase", "Material Purchase"),
                    ("Project Income", "Project Income"),
                    ("Food Expense", "Food Expense"),
                    ("Fuel Expense", "Fuel Expense"),
                    ("Labour Expense", "Labour Expense"),
                    ("Transport Expense", "Transport Expense"),
                    ("Owner Drawings", "Owner Drawings"),
                    ("Salary", "Salary"),
                ],
                db_index=True,
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="party_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Client", "Client"),
                    ("Supplier", "Supplier"),
                    ("Employee", "Employee"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Paid", "Paid"),
                    ("Partially Paid", "Partially Paid"),
                    ("Credit", "Credit"),
                    ("Unpaid", "Unpaid"),
                ],
                max_length=64,
            ),
        ),
    ]
